#!/bin/bash
#----------------------------------
#user command
USER_COMMAND=$1
#----------------------------------
DOCKER_IMAGE="rmoralesiaa/debian:lemon"
USER=lemon
#----------------------------------
XSOCK=/tmp/.X11-unix/X0
MY_DISPLAY=$DISPLAY
XAUTHORITY_DIR=/tmp/.X11-unix:/tmp/.X11-unix
XAUTHORITY_VOLUMEN="$HOME/.Xauthority:/root/.Xauthority:rw"
#----------------------------------
#link local directorioes with directories inside the docker. Format: local_dir:docker_dir
ASTROMETRY_NET_INDEX_DIR=/media/data/images/tools/astrometry.net/indexes_gaia_edr3/:/usr/local/astrometry/data
LEMON_DATA_IN=/home/rafa/apps/lemon/data/in/:/home/lemon/data/in
LEMON_DATA_OUT=/home/rafa/apps/lemon/data/out/:/home/lemon/data/out
#----------------------------------
sudo docker run \
 --user $USER \
 --net host \
 -e DISPLAY=$MY_DISPLAY \
 --volume=$XAUTHORITY_VOLUMEN \
 -v $XAUTHORITY_DIR \
 -v $ASTROMETRY_NET_INDEX_DIR \
 -v $LEMON_DATA_IN \
 -v $LEMON_DATA_OUT \
 -it $DOCKER_IMAGE \
 $USER_COMMAND
#----------------------------------
#end of file
